name: Mirror to Epitech Repo

on: 
    push: 
        branches: 
            - main

jobs:
  to_epitech:
    if: ${{ github.repository == 'Popolitics/documentation' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:EpitechMscProPromo2027/T-ESP-800-project-100846-NAN_Popolitics.git
          ssh_private_key:
            ${{ secrets.SSH_PRIVATE_KEY }}